import 'package:flutter/material.dart';

class model{

  static Color green= Color(0xff009788);
  static Color back_color= Color(0xffE0F2F2);

 static List photo = [
   "aguacate.png",
   "baloon.png",
   "banana.png",
   "bell.png",
   "bellota.png",
   "boat.png",
   "bucket.png",
   "burggar.png",
   "calabaza.png",
   "candle.png",
   "car.png",
   "caracol.png",
   "carate.png",
   "cat.png",
   "cerezas.png",
   "cheir.png",
   "chese.png",
   "chilli.png",
   "chocklet.png",
   "ciruela.png",
   "coco.png",
   "cow.png",
   "dog.png",
   "fen.png",
   "fish.png",
   "flower.png",
   "foot_ball.png",
   "grapes.png",
   "hill.png",
   "horse.png",
   "kabutar.png",
   "khishkoli.png",
   "lasan.png",
   "leaf.png",
   "magnat.png",
   "orange.png",
   "oreo.png",
   "oso.png",
   "pan.png",
   "parrot.png",
   "peon.png",
   "perfume.png",
   "pinguino.png",
   "play.png",
   "rose.png",
   "sars.png",
   "telefono.png",
   "troffy.png",
   "umrella.png",
   "watch.png",
  ];
}